version: '3'
services:
  web:
    build: .
    ports:
      - 8001:80
    links:
      - api
    depends_on:
      - api
  api:
    image: djwelsh/todo-api
    ports:
      - 3333:80
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo/todo"
      SECRET: "changethistosomethingmoresecret"
      DEBUG: "true"
      DB_TYPE: "MONGO"
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
