version: '3'
services:
  todos_api:
    image: djwelsh/todo-api
    ports:
      - 3333:80
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo/todo"
      SECRET: "changethistosomethingmoresecret"
      DEBUG: "true"
      DB_TYPE: "MONGO"

  todos_web:
    container_name: 'todos_web'
    image: djwelsh/todo-webapp
    links:
      - todos_api
    depends_on:
      - todos_api

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo:
